; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "rosetta"
; Version comes from Cargo.toml, passed in by the build as
;   ISCC /DMyAppVersion="x.y.z"
; The fallback below only applies when compiling setup.iss by hand.
#ifndef MyAppVersion
  #define MyAppVersion "0.0.0-dev"
#endif
#define MyAppPublisher "Elements S.R.L."
#define MyAppURL "https://elements-ic.com/"
#define MyAppExeName "rosetta.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{57490DA8-C0C3-4B29-94AF-C6FAEA8549A7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
SetupArchitecture=x64
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=target
OutputBaseFilename=rosetta_setup
SolidCompression=yes
WizardStyle=modern dynamic
; Broadcast WM_SETTINGCHANGE so new shells pick up the PATH change.
ChangesEnvironment=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "addtopath"; Description: "Add {#MyAppName} to PATH"; GroupDescription: "Command line:"

[Files]
Source: "target\release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "vendor\dlls\FTD2XX.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "vendor\dlls\MPSSE.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "vendor\dlls\okFrontPanel.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; PATH lives in a different hive depending on whether the user picked a
; per-user or an all-users install, so there is one entry for each.
; No uninsdeletevalue here: that would wipe the whole Path value, not just
; our segment. Removal is handled in [Code] below.
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; \
    ValueData: "{olddata};{app}"; Tasks: addtopath; Check: NeedsAddPathHKCU
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; \
    Tasks: addtopath; Check: NeedsAddPathHKLM

[Code]
const
  EnvKeyHKLM = 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment';

{ Semicolon-wrapped compare so C:\rosetta doesn't match inside C:\rosetta-old. }
function PathMissing(RootKey: Integer; SubKey: String): Boolean;
var
  OrigPath: String;
begin
  if not RegQueryStringValue(RootKey, SubKey, 'Path', OrigPath) then
  begin
    Result := True;
    exit;
  end;
  Result := Pos(';' + UpperCase(ExpandConstant('{app}')) + ';',
                ';' + UpperCase(OrigPath) + ';') = 0;
end;

function NeedsAddPathHKCU: Boolean;
begin
  Result := (not IsAdminInstallMode) and PathMissing(HKEY_CURRENT_USER, 'Environment');
end;

function NeedsAddPathHKLM: Boolean;
begin
  Result := IsAdminInstallMode and PathMissing(HKEY_LOCAL_MACHINE, EnvKeyHKLM);
end;

procedure RemoveFromPath(RootKey: Integer; SubKey: String);
var
  OrigPath, Work, Target: String;
  P: Integer;
begin
  if not RegQueryStringValue(RootKey, SubKey, 'Path', OrigPath) then exit;
  Target := ';' + UpperCase(ExpandConstant('{app}')) + ';';
  Work := ';' + OrigPath + ';';
  P := Pos(Target, UpperCase(Work));
  if P = 0 then exit;
  Delete(Work, P, Length(Target) - 1);
  RegWriteExpandStringValue(RootKey, SubKey, 'Path',
                            Copy(Work, 2, Length(Work) - 2));
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    { Removal is a no-op when our segment isn't there, so try HKCU either way
      rather than trusting the install mode to round-trip into the uninstaller. }
    RemoveFromPath(HKEY_CURRENT_USER, 'Environment');
    if IsAdminInstallMode then
      RemoveFromPath(HKEY_LOCAL_MACHINE, EnvKeyHKLM);
  end;
end;

